### ISSUE TITLE
组件的 size 是否可以跟随 elementui 的 size

### ISSUE THREAD

**Issue by zhuangjinming16** [GoldSubmarine/xcrud#4]
组件的 `size` 是否可以跟随 `elementui` 的 `size`  ，目前看，如果没有传入 `config` ，默认是 `medium`

**Comment by Nayacco** [comment]
是的，就是 `elementui` 的 `size`

**Comment by zhuangjinming16** [comment]
我的意思是，是否可以动态切换？我看到很多配置项都有`size `，都是独立配置的，如果统一配置，直接跟随 配置的 `size `，直接渲染，然后，size变化，crud 的跟着一起变化。

**Comment by Nayacco** [comment]
没看明白😓

**Comment by zhuangjinming16** [comment]
是这样，我自己用原生的elementui可以切换size，但 若同时用了，xcrud ，xcrud 无法一起切换size

**Comment by Nayacco** [comment]
xcrud中有好多按钮，你是配置的哪个地方的size呢？你是怎么配的呢？或许你可以贴一点代码说明

**Comment by zhuangjinming16** [comment]
是否可以，只改一个地方，所有都生效
